version: '2'
services:
    db:
        image: kvorobyev/autohome:db_master
        ports:
            - "54321:5432"
        volumes:
            - data-master:/data
    app:
        image: kvorobyev/autohome:poll_arm
        links:
            - db
volumes:
    data-master:

