version: '2'
services:
    db:
        image: kvorobyev/autohome:db_master
        ports:
            - "54321:5432"
        volumes:
            - data-master:/data
    app:
        image: kvorobyev/autohome:poll_arm
        privileged: true
        devices:
            - "/dev/rfcomm0"
            - "/dev/rfcomm1"
            - "/dev/rfcomm2"
            - "/dev/rfcomm3"
        links:
            - db
volumes:
    data-master:

